FROM ubuntu:24.04 

# Set the working directory in the container
WORKDIR /src

RUN apt-get update && apt-get install -y

RUN apt install -y python3 python3-pip python3-venv

# Create and activate a virtual environment
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN apt-get install -y wget curl
RUN apt-get install -y build-essential

RUN apt update
RUN apt install -y libcfitsio-dev libcfitsio-bin

RUN apt install -y git 
RUN git clone https://github.com/manodeep/Corrfunc.git

RUN apt-get install -y libgsl-dev
WORKDIR /src/Corrfunc
RUN make
RUN make install

RUN pip3 install .

WORKDIR /src

RUN apt install -y libopenmpi-dev

RUN pip3 install numpy==1.26.4 Cython==0.29.37 mpi4py setuptools

RUN git clone https://github.com/sbird/classylss.git
RUN (cd /src/classylss && pip3 install .)

RUN apt-get install -y libbz2-dev
RUN pip3 install --no-build-isolation nbodykit[extras]

RUN pip3 install matplotlib notebook